### ISSUE TITLE
root_probe_wdl

### ISSUE THREAD

**Issue by lucasart** [syzygy1/tb#1]
Hello,

Could you merge the changes root_probe_wdl (as well as the search.cpp SF example) into this repo ?

Thanks!

**Comment by syzygy1** [comment]
I've merged the root_probe_wdl() changes.
Apparently on some distributions fread() is declared with a special attribute to generate compiler warnings if its result is not used. Annoying. Since I have received no other reports of these warnings I'll leave it as it is for now. (The other warnings made a lot of people think there were errors in the code, so suppressing those was very useful ;-).)
